function YDM() {
  alert("YDM 4 LOCOMOTIVE") 
  alert("The class YDM-4 is Indian Railways' workhorse diesel locomotive. The first units were imported fully built from the American Locomotive Company (Alco) in 1961. Since 1968, it has been manufactured in India by the Banaras Locomotive Works (BLW), Varanasi. The model name stands for metre gauge (Y), diesel (D), mixed traffic (M) engine. The YDM-4 has been the most successful diesel locomotive in the metre gauge operation of Indian Railways. The YDM-4A is a variant of the YDM-4 supplied by MLW . Originally equipped with vacuum brakes. Some were later equipped with dual brakes, particularly those working in the Northeast Frontier Railway were retrofitted with dual brake system by Lumding shed. ") 
  alert("Maximum speed: 96 km/h")
  alert("Power output: 1,400 hp (1,000 kW)")
}

function WDGA() {
  alert("WDG 3A LOCOMOTIVE") 
  alert("The Indian locomotive class WDG-3A is a class of diesel-electric locomotive that was developed in 1994 by Banaras Locomotive Works (BLW),Varanasi for Indian Railways. The model name stands for broad-gauge (W), Diesel (D), Goods traffic (G) engine, 3100 Horsepower (3A) locomotive. hey entered service on 18 July 1995. A total of 1164 WDG-3A units were built between 1994 and 2015 at BLW, Varanasi with a few units being produced by Diesel Loco Modernisation Works (DLMW) and Parel Workshop. It is considered to be a successful locomotive class with high reliability and few maintenance problems. Despite the introduction of more modern types of locomotives like WDG-4 and electrification, a significant number are still in use, both in mainline and departmental duties. As of April 2022, 1047 locomotives still retain operational status on the mainline as WDG-3A, with a few examples having been converted to WAGC3 or WAG-10.") 
  
  alert("Maximum speed: 105 km/h")
    alert("Power output:3100 HP")
}
function WDGB() {
  alert("WDG 4 LOCOMOTIVE") 
  alert("Maximum speed: 105 km/h")
  alert("The Indian locomotive class WDG-4 (EMD GT46MAC) is a freight-hauling diesel-electric locomotive with AC electric transmission designed by General Motors Electro-Motive Diesel[1] in 1997–1998 for Indian Railways, where they are classed as WDG-4. Thirteen were built by EMD as order #958647, and a further eight were exported in kit form and assembled in India. The class entered service in 1999. Further construction has been under license in India by the Banaras Locomotive Works (BLW); more than 60 additional locomotives have been built as of 2006. They are numbered from #12001 upward. A similar type, the EMD GT46PAC, has also been produced for passenger service in India. Newer editions with 4,500 hp (3,400 kW) have been produced. Over 1,000 WDG-4 locomotives are currently in operation. ")
    alert("Power output: 4,500 hp (3,360 kW)")
}

function WDMA() {
  alert("WDM 2 LOCOMOTIVE") 
  alert("The Indian locomotive class WDM-2 is a class of diesel-electric locomotive that was developed in 1962 by American Locomotive Company (ALCO) for Indian Railways. The model name stands for broad gauge (W), Diesel (D), Mixed traffic (M) engine, 2nd generation (2). They entered service in 1962. A total of 2700+ WDM-2 was built at ALCO and Banaras Locomotive Works (BLW or DLW, as it was formerly Diesel Locomotive Works), Varanasi between 1962 and 1998, which made them the most numerous class of mainline diesel locomotive until its successor the WDM-3A. The WDM-2 is one of the most successful locomotives of Indian Railways serving both passenger and freight trains for over 60 years. A few WDM-2 units were exported to neighboring countries like Sri Lanka and Bangladesh. Despite the introduction of more modern types of locomotives like WDG-4 and electrification, a significant number are still in use, both in mainline and departmental duties. As of April 2022, 10 locomotives still retain operational status on the mainline as WDM-2. A number of WDM-2 locomotives have been preserved all over India with some units still in service. ")  
  alert("Maximum speed: 120 km/h")
    alert("Power output: 2,600 hp (1,900 kW)")
}
function WDMB() {
  alert("WDM 3A LOCOMOTIVE") 
  alert("The Indian locomotive class WDM-3A is a class of diesel–electric locomotive that was developed in 1993 by Banaras Locomotive Works (BLW), Varanasi for Indian Railways. The model name stands for broad gauge (W), Diesel (D), Mixed traffic (M) engine, with 3300 horsepower (3A). The WDM-3A is a later classification of earlier WDM-2C. They entered service in 1994. A total of 143+ were built at ALCO and Banaras Locomotive Works between 1994 and 2003 with rest of the 1246 units being rebuild from WDM-2 which made them the most numerous class of mainline diesel locomotive until the WDG-4. The WDM-3A is one of the most successful locomotives of Indian Railways serving both passenger and freight trains for over 26 years. A few WDM-3A units were exported to neighboring countries like Sri Lanka and Bangladesh. Despite the introduction of more modern types of locomotives like WDG-4 and electrification, a significant number are still in use, both in mainline and departmental duties. As of April 2022, 769 locomotives still retain operational status on the mainline as WDM-3A, with further examples having been converted back to WDM-2 or WDM-2S. The loco is now widely used across India for long-distance passenger trains due to its ruggedness and high tractive loads and acceleration. ") 
  alert("Maximum speed: 120 km/h")
  alert("Power output: 3100 HP")
}

function WDPA() {
  alert("WDP 1 LOCOMOTIVE") 
  alert("The Indian locomotive class WDP-1 is a class of diesel-electric locomotive that was developed in 1995 by Banaras Locomotive Works (BLW) for Indian Railways. The model name stands for broad gauge (W), Diesel (D), Passenger traffic (P) engine, 1st generation (1). They entered service in 1995. A total of 69 WDP-1 units were built at Banaras Locomotive Works (BLW), Varanasi between 1995 and 1999. The WDP-1 served both passenger and freight trains for over 25 years. Despite the introduction of more modern types of locomotives like WDG-4 and electrification, a significant number are still in use, both in mainline and departmental duties. As of April 2022, 57 locomotives still retain operational status on the mainline. WDP1M is a rebuilt version with better powerpack and better cooling via a modified radiator. The biggest change is in the suspension. Rubber springs have been provided instead of coil springs, along with other changes to the suspension and axle components. The scrapping of these locomotives has begun. ")  
  alert("Maximum speed: 140 km/h")
    alert("Power output: 2,300 hp (1,700 kW")
}
function WDPB() {
  alert("WDP 3A LOCOMOTIVE") 
  alert("The Indian locomotive class WDP-3A also known as Toaster is a class of diesel-electric locomotive that was developed in 1998 by Banaras Locomotive Works, Varanasi for Indian Railways. The model name stands for broad gauge (W), Diesel (D), Passengers traffic (P) locomotive with 3100 horsepower (3A). The WDP-3A is a later classification of earlier WDP-2. They entered service in 1998. A total of 44 were built between 1998 and 2001.They are the Fastest ALCo based locomotive found in India with a Top speed of 160 km/h, on par with the premier Electric Locomotives. The WDP-3A served IR for over 24 years. A significant number of these locomotives are still in use, both on mainline and departmental duties. As of June 2022, few of the locomotives still retain operational status on the mainline as WDP-3A, with further examples having been Scrapped. The WDP3A was best known for hauling the Trivandrum Rajdhani and later on the Mumbai CSMT - Karmali Tejas Express through the Konkan Railway at a top speed of 120 kmh single-handedly. In 2018, a couple of GOC Based WDP3A locomotives were rebuilt at DMW Patiala with better bogies for Riding comfort. Such Rebuilt toasters bear the suffix 'R' to their road numbers. All WDP-3A locomotives of KYN DLS were condemned in January 2022 and scrapped at DLS. ") 
  alert("Maximum speed: 160 km/h")
    alert("Power output: 3100 HP")
}

function WDPC() {
  alert("WDP 4 LOCOMOTIVE") 
  alert("The EMD GT46PAC or WDP4 is a passenger-hauling diesel-electric locomotive with AC electric transmission designed by General Motors Electro-Motive Division and built by both GM-EMD and under license by Banaras Locomotive Works (BLW) of Varanasi, India for Indian Railways as the classes WDP4, WDP4B and WDP4D.[1] The GT46PAC is a passenger version of the previous Indian Railways EMD GT46MAC freight locomotive. The locomotive has a 16-cylinder 710G3B diesel engine and is one of the fastest diesel-electric locomotives in service in Indian Railways. The WDP-4 was the loco originally designed by GM EMD and 10 of them were dispatched to India by June 2001. Later on Banaras Locomotive Works, Varanasi started building them initially using knocked-down kits and later indigenously. Starting 2003, the locomotives were produced in large numbers by BLW. The locomotive features self diagnostics control using EM2000 onboard microprocessor which was a new technology for Indian Railways back then. this loco has a Bo1-1Bo wheel arrangement meaning that it has two powered and one unpowered axle per bogie. This was done to reduce the weight of the loco to make it suitable for passenger operations and also to reduce maintenance. The first set of 10 locos starting from road number 20000 to 20009 were manufactured by the Electro Motive Diesel (EMD) of (General Motors) while road numbers 20011 upwards have been manufactured by Banaras Locomotive Works (DLW) of Varanasi in collaboration with GM (General motors). WDP 4B and WDP 4D are its varients. 710 locomotives are active.")  
  alert("Maximum speed: 180 km/h")
    alert("Power output: 4,000 hp (2,980 kW)");
}

function WDPD() {
  alert("WDG 6G LOCOMOTIVE") 
  alert("WDG-6G is a class of diesel-electric locomotive used by the Indian Railways for freight duty. The locomotive is a higher power variant of the WDG-4G locomotive which was also designed by General Electric. The design platform is based on the GE Evolution Series and features a 4-stroke 16-cylinder fully turbocharged engine which delivers around 6,000 horsepower.")  
  alert("Maximum speed: 100 km/h")
    alert("Power output: 6,000 hp (4,470 kW)")
}




function WAGA() {
  alert("WAG 5 LOCOMOTIVE") 
  alert("The Indian locomotive class WAG-5 is a class of 25 kV AC electric locomotives that was developed in 1978 by Chittaranjan Locomotive Works for Indian Railways. The model name stands for broad gauge (W), alternating current (A), goods traffic (G) engine, 5th generation (5). They entered service in 1980. A total of 1196 WAG-5 were built at CLW and BHEL between 1978 and 1998, which made them the most numerous class of mainline electric locomotive till its successor the WAG-7. The WAG-5 is one of the most successful locomotives of Indian Railways currently serving both freight and passenger trains for over 42 years. This class provided the basic design for a number of other locomotives, like WAG-7 and the WCM-6. However, with the advent of new 3-phase locomotives like WAG-9 and WAG-12, the WAG-5 locomotives were relegated to hauling smaller passenger trains and now the aging fleet the WAG-5 locomotives are slowly being withdrawn from mainline duties and scrapped. ") 
  alert("Maximum speed: 105 km/h")
  alert("Power output: 3,850 hp (2,870 kW)")
}

function WAGB() {
  alert("WAG 7 LOCOMOTIVE") 
  alert("The Indian locomotive class WAG-7 is a class of 25 kV AC electric locomotives that was developed in 1990 by Chittaranjan Locomotive Works for Indian Railways. The model name stands for broad gauge (W), alternating current (A), goods traffic (G) engine, 7th generation (7). They entered service in 1992. A total of 1970 WAG-7 were built at CLW and BHEL between 1990 and 2015, which made them the most numerous class of mainline electric locomotive till its successor the WAG-9. The WAG-7 is one of the most successful locomotives of Indian Railways currently serving both freight and passenger trains for over 30 years. Even though with the advent of new 3-phase locomotives like WAG-9 and WAG-12, all WAG-7 locomotives except ones destroyed in accidents, rest are in service and doing all types of duties. ")  
  alert("Maximum speed: 105 km/h")
    alert("Power output:5,350 hp (3,990 kW)")
}
function WAGC() {
  alert("WAG 9 LOCOMOTIVE") 
  alert("The Indian locomotive class WAG-9 is a class of 25 kV AC electric locomotives that was developed in 1995 by ABB Group (ABB) for Indian Railways. The model name stands for broad gauge (W), AC Current (A), Goods traffic (G), 9th generation (9) locomotive. They entered service in 1996. A total of 3434 WAG-9 have been built at Chittaranjan Locomotive Works (CLW), with more units being built at Banaras Locomotive Works (BLW), Bharat Heavy Electricals Limited (BHEL) and Patiala Locomotive Works (PLW). It was the most powerful freight locomotive of its fleet until the formal introduction of the WAG-12. The WAG-9 is one of the most successful locomotives of Indian Railways serving freight trains for over 26 years. A passenger variant of the WAG-9 was developed namely the WAP-7 locomotive by modifying the gear ratio to pull lighter loads at higher speeds. Nowadays, It is a common locomotive used in freight trains. WAG-9 has quickly become one of the important locos in the Indian railways. With its higher power, this locomotive has replaced WAG-7 which was the main electric loco before WAG-9's arrival. Applications where twin WAG-7s were required are now handled by a single WAG-9. This includes both leading a long consist and for banking operations. The regenerative braking capabilities of WAG-9 has also helped reduce the electricity consumption. The original WAG-9 had some wheel slippage incidents while hauling heavy load. This was rectified through the introduction of WAG-9H and subsequently using WAG-9i. This has significantly reduced the issue that were associated with the original version. The varients are - WAG 9H, WAG 9I, WAG 9HI, WAG 9 HH, WAG 9HC") 
  alert("Maximum speed: 100 km/h")
    alert("Power output:  6,122 hp (4,565 kW)")
}

function WAGD() {
  alert("WAG 12 LOCOMOTIVE") 
  alert("The Indian locomotive class WAG-12B is a class of 25 kV AC electric locomotives that was developed in 2017 by Alstom with technological collaboration with Indian Railways. The model name stands for broad gauge (W), Alternating Current (AC), Goods traffic (G) locomotive, 12000 hp (12). They entered trial service in 2019. A total of 250 WAG-12B have been built at Electric Locomotive Factory, Madhepura, Bihar, India. With a power output of 12,000 HP, the WAG 12 is twice as powerful as its immediate predecessor, WAG-9, and is among the most powerful freight locomotives in the world. The locomotive is being developed for deployment on the Dedicated Freight Corridors, where it will be used to haul freight trains weighing more than 6,000 tonnes (5,900 long tons; 6,600 short tons) at speeds of 100 km/h (62 mph) to 120 km/h (75 mph), essentially doubling the average speed of freight trains in the sector. They are three phase, twin-section electric freight locomotive consisting of two identical sections, each of which rests on two twin-axled Bo-Bo bogies. The locomotive is being jointly developed by Alstom and the Indian Railways, and is the first Indian Railways locomotive that has a power output greater than 10,000 horsepower. With a power output of 12,000 HP, it is twice as powerful as its immediate predecessor, WAG-9, and is one of the most powerful freight locomotives in the world")  
  alert("Maximum speed: 120 km/h")
    alert("Power output: 12,000 hp (8,950 kW)")
}
function WAM() {
  alert("WAM 4 LOCOMOTIVE") 
  alert("The Indian locomotive class WAM-4 is a class of 25 kV AC electric locomotives that was developed in 1970 by Chittaranjan Locomotive Works for Indian Railways. The model name stands for broad gauge (W), alternating current (A), mixed traffic (M) engine, 4th generation (4). They entered service in March 1971. A total of 500 WAM-4 were built at CLW between 1970 and 1983, which made them the most numerous class of mainline electric locomotive till its successor the WAG-5. The WAM-4 is one of the most successful locomotives of Indian Railways having served both passenger and freight trains for over 51 years. This class provided the basic design for a number of other locomotives like WCAM-1, WAG-5A, WCG-2, and some WAP-1 models. However, with the advent of new 3-phase locomotives like WAP-5 and WAP-7, the WAM-4 locomotives were relegated to hauling smaller passenger trains and now the aging fleet of WAM-4 locomotives are being rapidly scrapped and have been fully withdrawn from mainline duties. This loco has the widest variety of liveries, with each loco shed having its own livery. Most of the WAM-4 locomotives now have their MU capability disabled as RDSO disapproves of these locomotives running MU'd over 100 km/h") 
  alert("Maximum speed: 120 km/h")
  alert("Power output: 3,640 hp (2,710 kW)")
}

function WCAM() {
  alert("WCAM 3 LOCOMOTIVE") 
  alert("The Indian locomotive class WCAM–3 is a class of dual-power AC/DC series electric locomotives That was developed in 1997 by Bharat Heavy Electricals Limited used in the Indian Railways system. They are the third locomotives from the WCAM class. The model name stands for broad gauge (W), DC Current (C), AC Current (A), Mixed traffic (M) locomotive, 3rd generation (3). They entered service in 1997. A total of 53 WCAM-3 were built at BHEL between 1997 and 1998, which made them the most numerous class of mainline dual-power AC-DC electric locomotive. They were specifically designed for use by Central Railways in the Ghat section towards Nashik and Pune. The class are in active service in the Central Railway zone. CR uses WCAM-3 locos on Mumbai-Pune, Diva-Ratnagiri and Mumbai-Igatpuri sections which had ghat portions as well as speed restrictions of about 100 km/h. They also used to haul intercity trains out of Mumbai DC suburban region on Western as well as Central Railway which was on a 1.5 kV DC overhead system, as opposed to other parts of India which had 25 kV 50 Hz AC overhead.[1] WCAM engines now serve trains operating out of Chhatrapati Shivaji Maharaj Terminus (CSMT) and as bankers on Kasara-Igatpuri/Karjat-Lonavla section. Due to exclusivity in operation/maintenance of these locomotives, they do not go beyond the Central Railway's zone limits. These dual-traction models deliver 4600 hp in DC mode and 5000 hp in AC mode, and post 25 kV transformation, WCAMs were fully transformed into pure AC locomotives, and the performance was even more improved. ")  
  alert("Maximum speed: 105 km/h")
    alert("Power output: 5,350 hp (3,990 kW)")
}
function WAPA() {
  alert("WAP 4 LOCOMOTIVE") 
  alert("The Indian locomotive class WAP-4 is a class of 25 kV AC electric locomotives that was developed in 1993 by Chittaranjan Locomotive Works for Indian Railways. The model name stands for broad gauge (W), AC Current (A), Passenger traffic (P) engine, 4th generation (4). They entered service in late 1994. A total of 778 WAP-4 were built at CLW between 1993 and 2015, which made them the most numerous class of mainline electric passenger locomotive until the WAP-7. The WAP-4 is one of the most successful locomotives of Indian Railways serving both passenger and freight trains for over 28 years. This class provided the basic design for other locomotives like the WAP-6 . Despite the introduction of more modern types of locomotives like WAP-7, a significant number are still in use, both in mainline duties. Production of this class was halted in December 2015 with locomotive number 25051 being the last unit to be rolled out. As of September 2022, all locomotives except those lost in accidents still retain operational status on the mainline as WAP-4, with further examples having been converted from WAP-6. The WAP-4 class was developed after its predecessor, the WAP-1, was found inadequate to haul the longer, heavier express trains (24-26 coaches) that were becoming the mainstay of the Indian Railways network. The loco has a streamlined twin cab carbody design, with top-mounted headlamps. The first 150 or so units had the headlamp mounted at waist level, with the lights being mounted in a protruding nacelle. Later on the headlamps were placed in a recessed nacelle, and from road # 22573 onward, the headlamps were moved to the top. Newer locos also feature larger windshields, more spacious driver cabin with bucket type seats and ergonomic controls. The control panel also features a mix of digital and analog displays in newer units (all analog display in older versions). Recently as per directive received from Railway Board [RB] all the loco sheds holding WAP-4 type locomotive have started Mu [Multiple Unit] operations. This configuration of Mu WAP-4 locos are being used to haul medium tonnage faster freight trains across IR. The different locomotive sheds of WAP-4 are Arakkonam, Santragachi, Erode, MughalSarai, Howrah and Bhusaval. All WAP-4s are painted in the same red-black with a yellow/cream band livery, though the shade of the red will differ from shed to shed, from the blazing crimson red of Santragachi SRC/ER to the orange of Erode ED/SR.") 
  alert("Maximum speed: 140 km/h")
    alert("Power output:  5,050 hp (3,766 kW)")
}

function WAPB() {
  alert("WAP 5 LOCOMOTIVE") 
  alert("The Indian locomotive class WAP-5 is the name of a class of High Speed electric locomotives produced and used by Indian Railways. The first 10 locomotives were imported from ABB in Switzerland in 1995. They are supposed to be a variant of the Swiss Lok 2000 (Design concept) and German DB Class 120 (mechanical chassis). One of the notable features of WAP-5 is regenerative braking. Other notable features of this loco are the provision of taps from the main loco transformer for hotel load, pantry loads, flexible gear coupling, wheel-mounted disc brakes, and a potential for speed enhancement to 200 km/h (120 mph). Braking systems include 160 kN (36,000 lbf) regenerative brakes, loco disc brakes, automatic train air brakes, and a charged spring parking brake. On 3 July 2014, a WAP-5 set an Indian speed record by hauling a train from Delhi to Agra within 90 minutes at a speed of 160 km/h (99 mph). The Gatimaan Express and Bhopal Shatabdi trains hauled by WAP-5 locomotives travel at 160 km/h (99 mph) and 150 km/h (93 mph) respectively in the New Delhi - Agra Cantt section. In October 2015, Chittaranjan Locomotive Works rolled out a WAP-5 locomotive (no. 30086) with a gear ratio of 59:35:19 for speed operations up to 200 km/h (120 mph). The control software was also modified accordingly. Another locomotive (no. 30164) was rolled out with aerodynamic cab profile. This is just a trial and not intended for passenger use as the tracks are not supported in major routes. Two WAP-5 locomotives (no. 35012 and 35013) were given an asymmetric body design with an aerodynamic profile for one cab and a blunt profile for another cab at the opposite end, which is intended to be semi-permanently coupled with a train in normal operation (a similar design was previously used on the British Rail Class 91 locomotives). One locomotive will be placed on each end of the train to utilize a push-pull configuration for future Tejas Express services. The two locomotives have a power output of 6,000 horsepower (4,500 kW) and will have a maximum speed of 160 kilometres per hour (99 mph). These locomotives were inaugurated in October 2020 ")  
  alert("Maximum speed: Operational : 160 km/h (99 mph)   Trials: 184 km/h (114 mph)   Potential: 225 km/h (140 mph)")
    alert("Power output: 6,120 hp (4,564 kW)");
}

function WAPC() {
  alert("WAP 7 LOCOMOTIVE") 
  alert("The Indian locomotive class WAP-7 is a class of 25 kV AC electric locomotives that was developed in 1999 by Chittaranjan Locomotive Works (CLW) for Indian Railways. The model name stands for broad gauge (W), AC Current (A), Passenger traffic (P) engine, 7th generation (7). They entered service in 2000. A total of 1423 WAP-7 have been built, with more units being built at CLW, Banaras Locomotive Works (BLW) and Patiala Locomotive Works (PLW). The WAP-7 is one of the most successful locomotives of Indian Railways serving passenger trains for over 22 years. It is a passenger variant of the WAG-9 freight locomotive with a modified gear ratio to pull lighter loads at higher speeds. With an output of 6,350 hp (4,740 kW), it is the most powerful passenger locomotive in the Indian Railways fleet, and the most numerous passenger locomotive in India. The WAP-7 is capable of hauling 24 coach trains at speeds 110–140 km/h (68–87 mph). It is now largely used by Northern Railways (NR), South Central Railways (SCR), Central Railways (CR), South East Central Railways (SECR), South Eastern Railways (SER), West Central Railways (WCR), Eastern Railways (ER), Western Railways (WR), North Central Railways (NCR), South Western Railways (SWR), Southern Railways (SR), East Central Railways (ECR), East Coast Railways (ECoR), North Eastern Railways (NER) etc among other zones. As of October 2021, all of which are fitted with H-type transition couplers which are compatible with both screw coupling and centre-buffer coupling. In February 2017, Banaras Locomotive Works built their first WAP 7 class locomotive. In 2019, a variant of the WAP-7, designated the WAP-7HS, was introduced for higher speeds. The WAP-7HS has a max speed of 180 km/h (110 mph), and is capable of hauling a 24-car train at 160 km/h (99 mph) as opposed to the 140 km/h (87 mph) of the original. Indian Railways plans to use the WAP-7HS for Shatabdi, Rajdhani, and Duronto express trains. However, as of September 2022, it has not been confirmed if any others have been built, and the single completed WAP-7HS has stayed restricted to 130 km/h (81 mph).")  
  alert("Maximum speed: 180 km/h")
    alert("Power output:  6,350 hp (4,740 kW)")
}

function LOADER() {
 alert("Loading...") 
 alert("Click on the images to see more information")
  
}

